# IRS Form 990 - Bulk Download & ProPublica API

In [98]:
import xml.etree.ElementTree as ET
from pathlib import Path
import json
import re
import requests
import pandas as pd
from utility import propublica_endpoint

In [111]:
# Base path
curr_dir = Path()

# Form990 folders
form990_dir = curr_dir / 'Form990'
form990_input_dir = form990_dir / 'input'
form990_input_csv_dir = form990_input_dir / 'csv'
form990_input_xml_dir = form990_input_dir / 'xml'
form990_output_dir = form990_dir / 'output'

In [106]:
filer = []
business_officer = []
return_data = []
employee_data = []
full_break = False

for xml_file in form990_input_xml_dir.glob('*.xml'):
    # Obtain root of xml file
    xml = ET.parse(xml_file)
    root = xml.getroot()

    # Acquire namespace, if there
    try:
        namespace = re.search(r'\{.+\}', root.tag).group()
    except AttributeError:
        namespace = ''
    
    # xml paths
    xml_path_ReturnHeader = f'./{namespace}ReturnHeader/'
    xml_path_PreparerFirmGrp = xml_path_ReturnHeader + f'{namespace}PreparerFirmGrp/'
    xml_path_Filer = xml_path_ReturnHeader + f'{namespace}Filer'
    xml_path_BusinessOfficerGrp = xml_path_ReturnHeader + f'{namespace}BusinessOfficerGrp'
    xml_path_ReturnData = f'./{namespace}ReturnData'

    filer_content = {}
    business_officer_content = {}
    return_content = {}

    # * Filer
    # Expecting shallow nesting
    for filer_item in root.find(xml_path_Filer):
        if len(filer_item) >= 1:
            # TODO: Handle instances where item text is nothing as it's only a parent
            # TODO: Figure out why 'BusinessName' is added but not 'USAddress'
            for filer_subitem in filer_item:
                key = re.sub(namespace, '', filer_subitem.tag)
                filer_content[key] = filer_subitem.text

            continue

        key = re.sub(namespace, '', filer_item.tag)
        filer_content[key] = filer_item.text

    filer.append(filer_content)

    # TODO: Implement preparer gathering
    # # Get preparer EIN if present; we only expect a max of one
    # field = 'PreparerFirmEIN'
    # try:
    #     filer_content[field] = root.find(f'{xml_path_PreparerFirmGrp}{namespace}{field}').text
    # except AttributeError:
    #     filer_content[field] = None

    # * BusinessOfficerGrp
    for business_officer_grp_item in root.find(xml_path_BusinessOfficerGrp):
        business_officer_content['EIN'] = filer_content['EIN'] # Include FK reference
        if len(business_officer_grp_item) >= 1:
            for business_officer_grp_subitem in filer_item:
                key = re.sub(namespace, '', business_officer_grp_subitem.tag)
                business_officer_content[key] = business_officer_grp_subitem.text
            continue

        key = re.sub(namespace, '', business_officer_grp_item.tag)
        business_officer_content[key] = business_officer_grp_item.text

    business_officer.append(business_officer_content)

    # * ReturnData
    # Assign FK column
    return_content['EIN'] = filer_content['EIN']
    # Also pulling TaxYr and TaxPeriodBeginDt from ReturnHeader section as it seems relevant
    for field in ['TaxYr', 'TaxPeriodEndDt']:
        return_content[field] = root.find(f'{xml_path_ReturnHeader}{namespace}{field}').text

    # TODO: parse documentId class/id in element (e.g., "RetDoc1038000001")
    for return_data_section in root.find(xml_path_ReturnData):
        # e.g., IRS990, IRS990ScheduleA, ...
        section = re.sub(namespace, '', return_data_section.tag)
        
        if section == 'IRS990ScheduleB':
            # 501(c)(4)s don't disclose contributors publicly after 2019
            # https://www.shipmangoodwin.com/insights/irs-finalizes-form-990-donor-disclosure-tax-rules.html
            # TODO: Handle this information for older files that would have this information:
                # e.g., if TaxYr < 2019...
            continue

        return_content[section] = {}
        
        for return_data_field in return_data_section:
            data_field_key = re.sub(namespace, '', return_data_field.tag)
            if data_field_key == 'Form990PartVIISectionAGrp':
                employee_content = {}
                for employee_field in return_data_field:
                    # Attach FK reference
                    employee_content['EIN'] = filer_content['EIN']
                    employee_content['TaxYr'] = return_content['TaxYr']

                    employee_field_key = re.sub(namespace, '', employee_field.tag)
                    employee_content[employee_field_key] = employee_field.text
                    
                employee_data.append(employee_content)
                continue

            # E.g., 'DoingBusinessAsName', 'USAddress', ...
            if len(return_data_field) >= 1:
                for return_data_subfield in return_data_field:
                    # This should handle instances where child element is just 'TotalAmt', or any other generic tag
                    data_subfield_key = data_field_key + '_' + re.sub(namespace, '', return_data_subfield.tag)
                    return_content[section][data_subfield_key] = return_data_subfield.text
                continue

            return_content[section][data_field_key] = return_data_field.text


    return_data.append(return_content)

In [109]:
# Convert to dataframes where possible
filer = pd.DataFrame(filer)
business_officer = pd.DataFrame(business_officer)
return_data = pd.DataFrame(return_data)
employee_data = pd.DataFrame(employee_data)

In [124]:
# * Filer export
filer.to_csv(
    form990_input_csv_dir / f'form990_filer_sample.csv'
)

# * BusinessOfficer export
business_officer.to_csv(
    form990_input_csv_dir / f'form990_business_officer_sample.csv'
)

# * ReturnData export
schedules = return_data.columns[3:]

for schedule in schedules:
    schedule_data = return_data.loc[return_data[schedule].notna(), :]
    schedule_df = pd.concat(
        [
            schedule_data.iloc[:, [0, 1, 2]], # Id columns
            pd.json_normalize(schedule_data.loc[:, schedule])
        ],
        axis=1
    )

    # Don't need redundant identifiers
    if schedule != 'IRS990':
        schedule = re.sub('IRS990', '', schedule)

    # More generalize file organization
    if schedule[:-1] == 'Schedule':
        schedule_folder = form990_input_csv_dir / 'CommonSchedules'
    elif schedule in ['EZ', 'PF', 'T'] or schedule == 'TScheduleA':
        schedule_folder = form990_input_csv_dir / 'AlternativeFormTypes'
    elif 'Sch' in schedule: # Should handle full Schedule spelling and 'SubstantialContributorsSch' example
        schedule_folder = form990_input_csv_dir / 'OtherSchedules'
    elif schedule not in ['IRS990', 'IRS4562']:
        schedule_folder = form990_input_csv_dir / 'Other'
    
    # TODO: Clean up the conditionals
    if schedule not in ['IRS990', 'IRS4562']:
        # Handle cases where directory has not yet been made
        try:
            schedule_df.to_csv(
                schedule_folder / f'form990_{schedule}_sample.csv'
            )
        except OSError: # No directory
            Path.mkdir(schedule_folder)
            schedule_df.to_csv(
                schedule_folder / f'form990_{schedule}_sample.csv'
            )
    else:
        schedule_df.to_csv(
                form990_input_csv_dir / f'form990_{schedule}_sample.csv'
            )

# * BusinessOfficer export
employee_data.to_csv(
    form990_input_csv_dir / f'form990_employee_data_sample.csv'
)

In [50]:
# sample_eins = pd.DataFrame(
#     filer_and_preparer_eins,
#     columns = [
#         'filer_ein',
#         'preparer_ein'
#     ]
# )

# sample_eins.head()

   filer_ein preparer_ein
0  731102960    731589604
1  934867692    454570537
2  203718726    822396457
3  822204282          NaN
4  830317641    208019714

In [51]:
# sample_eins.to_csv(form990_input_dir / 'sample_eins.csv')

In [4]:
sample_eins = pd.read_csv(
    form990_input_dir / 'sample_eins.csv'
).iloc[:, [1, 2]]

sample_eins.head()

   filer_ein  preparer_ein
0  731102960   731589604.0
1  934867692   454570537.0
2  203718726   822396457.0
3  822204282           NaN
4  830317641   208019714.0

In [8]:
for filer_ein in sample_eins.loc[:, 'filer_ein']:
    url = propublica_endpoint('organization', str(filer_ein))
    organization = requests.get(
        url
    ).json()

    print(json.dumps(organization, indent=4))

    break

{
    "organization": {
        "id": 731102960,
        "ein": 731102960,
        "name": "Bright Sky Inc",
        "careofname": "% SHANNA RICE",
        "address": "PO BOX 829",
        "city": "Chickasha",
        "state": "OK",
        "zipcode": "73023-0829",
        "exemption_number": 0,
        "subsection_code": 3,
        "affiliation_code": 3,
        "classification_codes": "1000",
        "ruling_date": "1983-09-01",
        "deductibility_code": 1,
        "foundation_code": 17,
        "activity_codes": "602328000",
        "organization_code": 1,
        "exempt_organization_status_code": 1,
        "tax_period": "2025-06-01",
        "asset_code": 5,
        "income_code": 2,
        "filing_requirement_code": 2,
        "pf_filing_requirement_code": 0,
        "accounting_period": 6,
        "asset_amount": 977248,
        "income_amount": 24861,
        "revenue_amount": 24861,
        "ntee_code": "O20Z",
        "sort_name": null,
        "created_at": "2023-05-09T20:41:03.596Z",
        "updated_at": "2026-04-15T13:45:53.283Z",
        "data_source": "current_2026_04_15",
        "have_extracts": null,
        "have_pdfs": null,
        "latest_object_id": "202630149349301858"
    },
    "filings_with_data": [
        {
            "tax_prd": 202206,
            "tax_prd_yr": 2022,
            "formtype": 0,
            "pdf_url": null,
            "updated": "2023-08-07T19:45:10.737Z",
            "totrevenue": 5155,
            "totfuncexpns": 27465,
            "totassetsend": 774852,
            "totliabend": 0,
            "pct_compnsatncurrofcr": 0.0,
            "tax_pd": null,
            "subseccd": 3,
            "unrelbusinccd": "N",
            "initiationfees": 0,
            "grsrcptspublicuse": 0,
            "grsincmembers": 0,
            "grsincother": 0,
            "totcntrbgfts": 5000,
            "totprgmrevnue": 0,
            "invstmntinc": 155,
            "txexmptbndsproceeds": 0,
            "royaltsinc": 0,
            "grsrntsreal": 0,
            "grsrntsprsnl": 0,
            "rntlexpnsreal": 0,
            "rntlexpnsprsnl": 0,
            "rntlincreal": 0,
            "rntlincprsnl": 0,
            "netrntlinc": 0,
            "grsalesecur": 0,
            "grsalesothr": 0,
            "cstbasisecur": 0,
            "cstbasisothr": 0,
            "gnlsecur": 0,
            "gnlsothr": 0,
            "netgnls": 0,
            "grsincfndrsng": 0,
            "lessdirfndrsng": 0,
            "netincfndrsng": 0,
            "grsincgaming": 0,
            "lessdirgaming": 0,
            "netincgaming": 0,
            "grsalesinvent": 0,
            "lesscstofgoods": 0,
            "netincsales": 0,
            "miscrevtot11e": 0,
            "compnsatncurrofcr": 0,
            "othrsalwages": 0,
            "payrolltx": 0,
            "profndraising": 0,
            "txexmptbndsend": 0,
            "secrdmrtgsend": 0,
            "unsecurednotesend": 0,
            "retainedearnend": 0,
            "totnetassetend": 774852,
            "nonpfrea": "07",
            "gftgrntsrcvd170": 345848,
            "txrevnuelevied170": 0,
            "srvcsval170": 0,
            "grsinc170": 211,
            "grsrcptsrelated170": 0,
            "totgftgrntrcvd509": 0,
            "grsrcptsadmissn509": 0,
            "txrevnuelevied509": 0,
            "srvcsval509": 0,
            "subtotsuppinc509": 0,
            "totsupp509": 0,
            "ein": 731102960
        },
        {
            "tax_prd": 202106,
            "tax_prd_yr": 2021,
            "formtype": 0,
            "pdf_url": null,
            "updated": "2022-07-01T20:37:04.630Z",
            "totrevenue": 258439,
            "totfuncexpns": 28434,
            "totassetsend": 805033,
            "totliabend": 8124,
            "pct_compnsatncurrofcr": 0.0,
            "tax_pd": null,
            "subseccd": 3,
            "unrelbusinccd": "N",
            "initiationfees": 0,
            "grsrcptspublicuse": 0,
            "grsincmembers": 0,
            "grsincother": 0,
            "totcntrbgfts": 258439,
            "totprgmrevnue": 0,
            "invstmntinc": 0,
            "txexmptbndsproceeds": 0,
            "royaltsinc": 0,
            "grsrntsreal": 0,
            "grsrntsprsnl": 0,
            "rntlexpnsreal": 0,
            "rntlexpnsprsnl": 0,
            "rntlincreal": 0,
            "rntlincprsnl": 0,
            "netrntlinc": 0,
            "grsalesecur": 0,
            "grsalesothr": 0,
            "cstbasisecur": 0,
            "cstbasisothr": 0,
            "gnlsecur": 0,
            "gnlsothr": 0,
            "netgnls": 0,
            "grsincfndrsng": 0,
            "lessdirfndrsng": 0,
            "netincfndrsng": 0,
            "grsincgaming": 0,
            "lessdirgaming": 0,
            "netincgaming": 0,
            "grsalesinvent": 0,
            "lesscstofgoods": 0,
            "netincsales": 0,
            "miscrevtot11e": 0,
            "compnsatncurrofcr": 0,
            "othrsalwages": 0,
            "payrolltx": 0,
            "profndraising": 0,
            "txexmptbndsend": 0,
            "secrdmrtgsend": 7834,
            "unsecurednotesend": 0,
            "retainedearnend": 0,
            "totnetassetend": 796909,
            "nonpfrea": "7",
            "gftgrntsrcvd170": 343121,
            "txrevnuelevied170": 0,
            "srvcsval170": 0,
            "grsinc170": 56,
            "grsrcptsrelated170": 0,
            "totgftgrntrcvd509": 0,
            "grsrcptsadmissn509": 0,
            "txrevnuelevied509": 0,
            "srvcsval509": 0,
            "subtotsuppinc509": 0,
            "totsupp509": 0,
            "ein": 731102960
        },
        {
            "tax_prd": 202006,
            "tax_prd_yr": 2020,
            "formtype": 0,
            "pdf_url": "https://projects.propublica.org/nonprofits/download-filing?path=04_2021_prefixes_72-74%2F731102960_202006_990_2021041217926789.pdf",
            "updated": "2022-07-01T20:37:04.630Z",
            "totrevenue": 26538,
            "totfuncexpns": 29263,
            "totassetsend": 594135,
            "totliabend": 27231,
            "pct_compnsatncurrofcr": 0.0,
            "tax_pd": null,
            "subseccd": 3,
            "unrelbusinccd": "N",
            "initiationfees": 0,
            "grsrcptspublicuse": 0,
            "grsincmembers": 0,
            "grsincother": 0,
            "totcntrbgfts": 26521,
            "totprgmrevnue": 0,
            "invstmntinc": 17,
            "txexmptbndsproceeds": 0,
            "royaltsinc": 0,
            "grsrntsreal": 0,
            "grsrntsprsnl": 0,
            "rntlexpnsreal": 0,
            "rntlexpnsprsnl": 0,
            "rntlincreal": 0,
            "rntlincprsnl": 0,
            "netrntlinc": 0,
            "grsalesecur": 0,
            "grsalesothr": 0,
            "cstbasisecur": 0,
            "cstbasisothr": 0,
            "gnlsecur": 0,
            "gnlsothr": 0,
            "netgnls": 0,
            "grsincfndrsng": 0,
            "lessdirfndrsng": 0,
            "netincfndrsng": 0,
            "grsincgaming": 0,
            "lessdirgaming": 0,
            "netincgaming": 0,
            "grsalesinvent": 0,
            "lesscstofgoods": 0,
            "netincsales": 0,
            "miscrevtot11e": 0,
            "compnsatncurrofcr": 0,
            "othrsalwages": 0,
            "payrolltx": 0,
            "profndraising": 0,
            "txexmptbndsend": 0,
            "secrdmrtgsend": 8156,
            "unsecurednotesend": 0,
            "retainedearnend": 0,
            "totnetassetend": 566904,
            "nonpfrea": "7",
            "gftgrntsrcvd170": 100894,
            "txrevnuelevied170": 0,
            "srvcsval170": 0,
            "grsinc170": 56,
            "grsrcptsrelated170": 0,
            "totgftgrntrcvd509": 0,
            "grsrcptsadmissn509": 0,
            "txrevnuelevied509": 0,
            "srvcsval509": 0,
            "subtotsuppinc509": 0,
            "totsupp509": 0,
            "ein": 731102960
        },
        {
            "tax_prd": 201906,
            "tax_prd_yr": 2019,
            "formtype": 0,
            "pdf_url": "https://projects.propublica.org/nonprofits/download-filing?path=01_2020_prefixes_72-74%2F731102960_201906_990_2020012817081120.pdf",
            "updated": "2021-08-30T18:32:59.682Z",
            "totrevenue": 37951,
            "totfuncexpns": 30886,
            "totassetsend": 621634,
            "totliabend": 52005,
            "pct_compnsatncurrofcr": 0.0,
            "tax_pd": null,
            "subseccd": 3,
            "unrelbusinccd": "N",
            "initiationfees": 0,
            "grsrcptspublicuse": 0,
            "grsincmembers": 0,
            "grsincother": 0,
            "totcntrbgfts": 37920,
            "totprgmrevnue": 0,
            "invstmntinc": 31,
            "txexmptbndsproceeds": 0,
            "royaltsinc": 0,
            "grsrntsreal": 0,
            "grsrntsprsnl": 0,
            "rntlexpnsreal": 0,
            "rntlexpnsprsnl": 0,
            "rntlincreal": 0,
            "rntlincprsnl": 0,
            "netrntlinc": 0,
            "grsalesecur": 0,
            "grsalesothr": 0,
            "cstbasisecur": 0,
            "cstbasisothr": 0,
            "gnlsecur": 0,
            "gnlsothr": 0,
            "netgnls": 0,
            "grsincfndrsng": 0,
            "lessdirfndrsng": 0,
            "netincfndrsng": 0,
            "grsincgaming": 0,
            "lessdirgaming": 0,
            "netincgaming": 0,
            "grsalesinvent": 0,
            "lesscstofgoods": 0,
            "netincsales": 0,
            "miscrevtot11e": 0,
            "compnsatncurrofcr": 0,
            "othrsalwages": 0,
            "payrolltx": 0,
            "profndraising": 0,
            "txexmptbndsend": 0,
            "secrdmrtgsend": 37336,
            "unsecurednotesend": 0,
            "retainedearnend": 0,
            "totnetassetend": 569629,
            "nonpfrea": "07",
            "gftgrntsrcvd170": 85374,
            "txrevnuelevied170": 0,
            "srvcsval170": 0,
            "grsinc170": 42,
            "grsrcptsrelated170": 0,
            "totgftgrntrcvd509": 0,
            "grsrcptsadmissn509": 0,
            "txrevnuelevied509": 0,
            "srvcsval509": 0,
            "subtotsuppinc509": 0,
            "totsupp509": 0,
            "ein": 731102960
        },
        {
            "tax_prd": 201806,
            "tax_prd_yr": 2018,
            "formtype": 0,
            "pdf_url": "https://projects.propublica.org/nonprofits/download-filing?path=12_2018_prefixes_68-74%2F731102960_201806_990_2018121816014622.pdf",
            "updated": "2019-10-15T18:25:41.970Z",
            "totrevenue": 29842,
            "totfuncexpns": 33301,
            "totassetsend": 648686,
            "totliabend": 86122,
            "pct_compnsatncurrofcr": 0.0,
            "tax_pd": null,
            "subseccd": 3,
            "unrelbusinccd": "N",
            "initiationfees": 0,
            "grsrcptspublicuse": 0,
            "grsincmembers": 0,
            "grsincother": 0,
            "totcntrbgfts": 11864,
            "totprgmrevnue": 0,
            "invstmntinc": 8,
            "txexmptbndsproceeds": 0,
            "royaltsinc": 0,
            "grsrntsreal": 17970,
            "grsrntsprsnl": 0,
            "rntlexpnsreal": 0,
            "rntlexpnsprsnl": 0,
            "rntlincreal": 17970,
            "rntlincprsnl": 0,
            "netrntlinc": 17970,
            "grsalesecur": 0,
            "grsalesothr": 0,
            "cstbasisecur": 0,
            "cstbasisothr": 0,
            "gnlsecur": 0,
            "gnlsothr": 0,
            "netgnls": 0,
            "grsincfndrsng": 0,
            "lessdirfndrsng": 0,
            "netincfndrsng": 0,
            "grsincgaming": 0,
            "lessdirgaming": 0,
            "netincgaming": 0,
            "grsalesinvent": 0,
            "lesscstofgoods": 0,
            "netincsales": 0,
            "miscrevtot11e": 0,
            "compnsatncurrofcr": 0,
            "othrsalwages": 0,
            "payrolltx": 0,
            "profndraising": 0,
            "txexmptbndsend": 0,
            "secrdmrtgsend": 71453,
            "unsecurednotesend": 0,
            "retainedearnend": 0,
            "totnetassetend": 562564,
            "nonpfrea": "7",
            "gftgrntsrcvd170": 71654,
            "txrevnuelevied170": 0,
            "srvcsval170": 0,
            "grsinc170": 13,
            "grsrcptsrelated170": 0,
            "totgftgrntrcvd509": 0,
            "grsrcptsadmissn509": 0,
            "txrevnuelevied509": 0,
            "srvcsval509": 0,
            "subtotsuppinc509": 0,
            "totsupp509": 0,
            "ein": 731102960
        },
        {
            "tax_prd": 201706,
            "tax_prd_yr": 2017,
            "formtype": 0,
            "pdf_url": "https://projects.propublica.org/nonprofits/download-filing?path=IRS%2F731102960_201706_990_2017112814982403.pdf",
            "updated": "2018-12-10T23:08:44.062Z",
            "totrevenue": 23073,
            "totfuncexpns": 28828,
            "totassetsend": 670946,
            "totliabend": 104923,
            "pct_compnsatncurrofcr": 0.0,
            "tax_pd": null,
            "subseccd": 3,
            "unrelbusinccd": "N",
            "initiationfees": 0,
            "grsrcptspublicuse": 0,
            "grsincmembers": 0,
            "grsincother": 0,
            "totcntrbgfts": 23073,
            "totprgmrevnue": 0,
            "invstmntinc": 0,
            "txexmptbndsproceeds": 0,
            "royaltsinc": 0,
            "grsrntsreal": 0,
            "grsrntsprsnl": 0,
            "rntlexpnsreal": 0,
            "rntlexpnsprsnl": 0,
            "rntlincreal": 0,
            "rntlincprsnl": 0,
            "netrntlinc": 0,
            "grsalesecur": 0,
            "grsalesothr": 0,
            "cstbasisecur": 0,
            "cstbasisothr": 0,
            "gnlsecur": 0,
            "gnlsothr": 0,
            "netgnls": 0,
            "grsincfndrsng": 0,
            "lessdirfndrsng": 0,
            "netincfndrsng": 0,
            "grsincgaming": 0,
            "lessdirgaming": 0,
            "netincgaming": 0,
            "grsalesinvent": 0,
            "lesscstofgoods": 0,
            "netincsales": 0,
            "miscrevtot11e": 0,
            "compnsatncurrofcr": 0,
            "othrsalwages": 0,
            "payrolltx": 0,
            "profndraising": 0,
            "txexmptbndsend": 0,
            "secrdmrtgsend": 104633,
            "unsecurednotesend": 0,
            "retainedearnend": 0,
            "totnetassetend": 566023,
            "nonpfrea": "7",
            "gftgrntsrcvd170": 64484,
            "txrevnuelevied170": 0,
            "srvcsval170": 0,
            "grsinc170": 24694,
            "grsrcptsrelated170": 0,
            "totgftgrntrcvd509": 0,
            "grsrcptsadmissn509": 0,
            "txrevnuelevied509": 0,
            "srvcsval509": 0,
            "subtotsuppinc509": 0,
            "totsupp509": 0,
            "ein": 731102960
        },
        {
            "tax_prd": 201606,
            "tax_prd_yr": 2016,
            "formtype": 0,
            "pdf_url": "https://projects.propublica.org/nonprofits/download-filing?path=2017_01_EO%2F73-1102960_990_201606.pdf",
            "updated": "2017-06-30T00:35:40.018Z",
            "totrevenue": 29495,
            "totfuncexpns": 44024,
            "totassetsend": 692641,
            "totliabend": 120863,
            "pct_compnsatncurrofcr": 0.0,
            "tax_pd": null,
            "subseccd": 3,
            "unrelbusinccd": "N",
            "initiationfees": 0,
            "grsrcptspublicuse": 0,
            "grsincmembers": 0,
            "grsincother": 0,
            "totcntrbgfts": 29493,
            "totprgmrevnue": 0,
            "invstmntinc": 2,
            "txexmptbndsproceeds": 0,
            "royaltsinc": 0,
            "grsrntsreal": 0,
            "grsrntsprsnl": 0,
            "rntlexpnsreal": 0,
            "rntlexpnsprsnl": 0,
            "rntlincreal": 0,
            "rntlincprsnl": 0,
            "netrntlinc": 0,
            "grsalesecur": 0,
            "grsalesothr": 0,
            "cstbasisecur": 0,
            "cstbasisothr": 0,
            "gnlsecur": 0,
            "gnlsothr": 0,
            "netgnls": 0,
            "grsincfndrsng": 0,
            "lessdirfndrsng": 0,
            "netincfndrsng": 0,
            "grsincgaming": 0,
            "lessdirgaming": 0,
            "netincgaming": 0,
            "grsalesinvent": 0,
            "lesscstofgoods": 0,
            "netincsales": 0,
            "miscrevtot11e": 0,
            "compnsatncurrofcr": 0,
            "othrsalwages": 0,
            "payrolltx": 0,
            "profndraising": 0,
            "txexmptbndsend": 0,
            "secrdmrtgsend": 120573,
            "unsecurednotesend": 0,
            "retainedearnend": 0,
            "totnetassetend": 571778,
            "nonpfrea": "7",
            "gftgrntsrcvd170": 142891,
            "txrevnuelevied170": 0,
            "srvcsval170": 0,
            "grsinc170": 24739,
            "grsrcptsrelated170": 0,
            "totgftgrntrcvd509": 0,
            "grsrcptsadmissn509": 0,
            "txrevnuelevied509": 0,
            "srvcsval509": 0,
            "subtotsuppinc509": 0,
            "totsupp509": 0,
            "ein": 731102960
        },
        {
            "tax_prd": 201506,
            "tax_prd_yr": 2015,
            "formtype": 0,
            "pdf_url": "https://projects.propublica.org/nonprofits/download-filing?path=2015_10_EO%2F73-1102960_990_201506.pdf",
            "updated": "2017-06-30T00:21:25.301Z",
            "totrevenue": 11003,
            "totfuncexpns": 71980,
            "totassetsend": 729517,
            "totliabend": 143210,
            "pct_compnsatncurrofcr": 0.0,
            "tax_pd": null,
            "subseccd": 3,
            "unrelbusinccd": "N",
            "initiationfees": 0,
            "grsrcptspublicuse": 0,
            "grsincmembers": 0,
            "grsincother": 0,
            "totcntrbgfts": 11000,
            "totprgmrevnue": 0,
            "invstmntinc": 3,
            "txexmptbndsproceeds": 0,
            "royaltsinc": 0,
            "grsrntsreal": 0,
            "grsrntsprsnl": 0,
            "rntlexpnsreal": 0,
            "rntlexpnsprsnl": 0,
            "rntlincreal": 0,
            "rntlincprsnl": 0,
            "netrntlinc": 0,
            "grsalesecur": 0,
            "grsalesothr": 0,
            "cstbasisecur": 0,
            "cstbasisothr": 0,
            "gnlsecur": 0,
            "gnlsothr": 0,
            "netgnls": 0,
            "grsincfndrsng": 0,
            "lessdirfndrsng": 0,
            "netincfndrsng": 0,
            "grsincgaming": 0,
            "lessdirgaming": 0,
            "netincgaming": 0,
            "grsalesinvent": 0,
            "lesscstofgoods": 0,
            "netincsales": 0,
            "miscrevtot11e": 0,
            "compnsatncurrofcr": 0,
            "othrsalwages": 0,
            "payrolltx": 0,
            "profndraising": 0,
            "txexmptbndsend": 0,
            "secrdmrtgsend": 142920,
            "unsecurednotesend": 0,
            "retainedearnend": 0,
            "totnetassetend": 586307,
            "nonpfrea": "7",
            "gftgrntsrcvd170": 126680,
            "txrevnuelevied170": 0,
            "srvcsval170": 0,
            "grsinc170": 24739,
            "grsrcptsrelated170": 0,
            "totgftgrntrcvd509": 0,
            "grsrcptsadmissn509": 0,
            "txrevnuelevied509": 0,
            "srvcsval509": 0,
            "subtotsuppinc509": 0,
            "totsupp509": 0,
            "ein": 731102960
        },
        {
            "tax_prd": 201406,
            "tax_prd_yr": 2014,
            "formtype": 0,