In [1]:
import xml.etree.ElementTree as ET
from pathlib import Path
import pandas as pd
from form990_parser import (
    parse_header,
    parse_return,
    get_org_type
)

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
xml_data_directory = Path(r'xml')

In [4]:
header_data = []
return_data = []
employee_data = []
contractor_data = []
expense_data = []
balance_sheet_data = []

for year_dir in xml_data_directory.iterdir():
    for period_dir in year_dir.iterdir():
        print(period_dir)
        counter = 0
        files_skipped = 0
        for xml_file in period_dir.glob('*.xml'):
            # Skip certain orgs and form types
            root = ET.parse(xml_file).getroot()
            org_type = get_org_type(root)
            if org_type not in ['501c3', '501c4', '527']:
                files_skipped += 1
                continue 

            if counter >= 50:
                break
            counter += 1

            # * Header
            header_content = parse_header(root, xml_file, org_type)
            header_data.append(header_content)

            # * Return
            if parse_return(root, 'tbd') is None:
                continue # Some files pertain to other types of returns (e.g., 990-T)
            return_content, employee_content, contractor_content, expense_content, balance_sheet_content = parse_return(root, 'tbd')
            return_data.append(return_content)
            
            # * Employee
            employee_data += employee_content
            
            # * Contractor
            contractor_data += contractor_content

            # * Expenses
            expense_data += expense_content
            
            # * Balance Sheet
            balance_sheet_data += balance_sheet_content
        # print(counter) # Uncomment when you want to know the actual number of files
        print(f"# Files skipped: {files_skipped}")

xml\2020\2020_1A
# Files skipped: 0
xml\2020\2020_3A
# Files skipped: 11
xml\2024\2024_01A
# Files skipped: 69
xml\2024\2024_02A
# Files skipped: 93
xml\2025\2025_01A
# Files skipped: 113
xml\2025\2025_02A
# Files skipped: 116
xml\2025\2025_03A
# Files skipped: 193
xml\2025\2025_04A
# Files skipped: 191
xml\2025\2025_05A
# Files skipped: 294
xml\2025\2025_05B
# Files skipped: 12
xml\2025\2025_06A
# Files skipped: 142
xml\2025\2025_07A
# Files skipped: 248
xml\2025\2025_08A
# Files skipped: 135
xml\2025\2025_09A
# Files skipped: 139
xml\2025\2025_10A
# Files skipped: 162
xml\2025\2025_11A
# Files skipped: 179
xml\2025\2025_11B
# Files skipped: 12
xml\2025\2025_11C
# Files skipped: 327
xml\2025\2025_11D
# Files skipped: 136
xml\2025\2025_12A
# Files skipped: 112
xml\2026\2026_1A
# Files skipped: 112
xml\2026\2026_2A
# Files skipped: 79
xml\2026\2026_3A
# Files skipped: 178
xml\2026\2026_4A
# Files skipped: 177

In [5]:
pd.DataFrame(header_data)

,FilerEIN,TaxPeriodBeginDate,TaxPeriodEndDate,TaxYear,ReturnType,FilerBusinessNameLine1Txt,FilerBusinessNameLine2Txt,FilerPhone,FilerAddressLine1Txt,FilerCity,...,PreparerCity,PreparerStateCode,PreparerZipCode,BusinessOfficerName,BusinessOfficerTitle,BusinessOfficerPhone,BusinessOfficerSignatureDate,org_type,file_name,NumOfficers
0,742044647,2018-07-01,2019-06-30,2018,990,NATIONAL JEWISH HEALTH,NaN,3033884461,1400 JACKSON STREET,DENVER,...,NaN,NaN,NaN,Christine Forkner,Chief Financial Officer,3033981004,2020-06-02,501c3,xml\2020\2020_3A\202011559349300711_public.xml,1
1,581416325,2019-01-01,2019-12-31,2019,990,HAWTREE VOLUNTEER FIRE DEPARTMENT INC,NaN,2522573288,PO BOX 116,WISE,...,HENDERSON,NC,27536,STEVE BARNEY,CHIEF,2524325386,2020-05-27,501c3,xml\2020\2020_3A\202011559349300716_public.xml,1
2,223139262,2018-07-01,2019-06-30,2018,990,RURAL DEVELOPMENT INC,NaN,4138639781,241 MILLERS FALLS ROAD,TURNERS FALLS,...,WESTBOROUGH,MA,01581,GINA GOVONI,EXECUTIVE DIRECTOR,4138639781,2020-05-06,501c3,xml\2020\2020_3A\202011559349300726_public.xml,1
3,363244264,2018-07-01,2019-06-30,2018,990,WILL COUNTY GOVERNMENTAL LEAGUE,NaN,8152547700,15905 S FREDERICK STREET Suite 107,PLAINFIELD,...,Oakbrook Terrace,IL,601815209,JOHN NOAK,PRESIDENT,8157293535,2020-05-15,501c4,xml\2020\2020_3A\202011559349300731_public.xml,1
4,043316917,2019-01-01,2019-12-31,2019,990,I'M STILL HERE FOUNDATION INC,NaN,7815690229,10 TOWER OFFICE PARK NO 317,WOBURN,...,BOSTON,MA,02109,JACQUELINE VISCHER,TREASURER,7815690229,2020-05-21,501c3,xml\2020\2020_3A\202011559349300736_public.xml,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1145,341577595,2024-07-01,2025-06-30,2024,990,STARK STATE COLLEGE FOUNDATION,NaN,3304946170,6200 Frank Ave NW,North Canton,...,NaN,NaN,NaN,Joseph Richards,Comptroller,3304946170,2026-03-05,501c3,xml\2026\2026_4A\202600869349300520_public.xml,1
1146,721362424,2025-01-01,2025-12-31,2025,990,NORCO CIVIC ASSOCIATION,NaN,9857649696,PO BOX 22,NORCO,...,NORCO,LA,70079,CLARENCE DUPEPE,TREASURER,9857649696,2026-03-24,501c4,xml\2026\2026_4A\202600869349300525_public.xml,1
1147,980142381,2025-01-01,2025-12-31,2025,990,BETHSHEAN MEXICO MISSION INC,NaN,7062555330,PO BOX 7391,ATHENS,...,HARTWELL,GA,30643,DAN GILLAND,SEC/TREASURER,NaN,2026-03-12,501c3,xml\2026\2026_4A\202600869349300535_public.xml,1
1148,631288598,2025-07-01,2025-09-30,2025,990,C A S A OF FLORENCE LAUDERDALE,NaN,2567650041,102 JACKSON COURT,SHEFFIELD,...,FLORENCE,AL,35630,HEATHER BEGLEY,DIRECTOR,2567650041,2026-03-11,501c3,xml\2026\2026_4A\202600869349300540_public.xml,1
1149,823560034,2025-01-01,2025-12-31,2025,990,MISSION PRODUCE FOUNDATION,NaN,8059813650,2710 CAMINO DEL SOL DR,OXNARD,...,WOODLAND HILLS,CA,91367,JOANNE WU,DIRECTOR,8059813650,2026-03-26,501c3,xml\2026\2026_4A\202600869349300545_public.xml,1

In [6]:
pd.DataFrame(return_data).head()

,PrincipalOfficer,PrincipalOfficerAddress,PrincipalOfficerCity,PrincipalOfficerStateCode,PrincipalOfficerZipCode,GrossReceiptsAmt,ActivityOrMission,MissionDesc,FormationYear,VotingMembersGoverningBodyCnt,...,RelatedOrganizationsAmt,GovernmentGrantsAmt,AllOtherContributionsAmt,NoncashContributionsAmt,TotalContributionsAmt,TotalProgramServiceRevenueAmt,TotalRevenueColumnAmt,RelatedOrExemptFuncIncomeAmt,UnrelatedBusinessRevenueAmt,ExclusionAmt
0,Christine Forkner,1400 Jackson Street,Denver,CO,80206,326863373,National Jewish Health's mission since 1899 is...,National Jewish Health's mission since 1899 is...,1978,44,...,0,60946782,29837556,3056144,96842809,192033726,298202040,187160868,4759037,9439326
1,STEVE BARNEY,PO BOX 116,WISE,NC,27594,107616,TO PROVIDE FIRE DEPARTMENT SERVICES FOR THE CO...,TO PROVIDE FIRE DEPARTMENT SERVICES FOR THE CO...,1981,9,...,NaN,15249,75692,NaN,90941,NaN,103997,3630,0,9426
2,GINA GOVONI,241 MILLERS FALLS ROAD,TURNERS FALLS,MA,01376,301633,"IT IS THE MISSION OF RURAL DEVELOPMENT, INC. (...",IT IS THE MISSION OF RDI TO ADVANCE THE RIGHT ...,1991,8,...,NaN,NaN,6470,NaN,6470,292417,301633,294917,0,246
3,JOHN NOAK,15905 S FREDRICK STREET 107,PLAINFIELD,IL,60586,740025,GOVERNMENT SERVICE,THE WILL COUNTY GOVERNMENTAL LEAGUE IS ORGANIZ...,1983,9,...,NaN,152971,NaN,NaN,152971,472601,664134,472601,NaN,38562
4,JACQUELINE VISCHER,10 TOWER OFFICE PARK NO 317,WOBURN,MA,01801,18632,TO BRING ABOUT COMMUNITY TRANSFORMATION FOR TH...,TO BRING ABOUT COMMUNITY TRANSFORMATION FOR TH...,1995,6,...,NaN,NaN,12724,NaN,12724,5908,18632,5908,0,0

In [7]:
pd.DataFrame(employee_data)

,EIN,PersonNm,TitleTxt,AverageHoursPerWeekRt,AverageHoursPerWeekRltdOrgRt,IndividualTrusteeOrDirectorInd,ReportableCompFromOrgAmt,ReportableCompFromRltdOrgAmt,OtherCompensationAmt,OfficerInd,KeyEmployeeInd,HighestCompensatedEmployeeInd,FormerOfcrDirectorTrusteeInd,BusinessName,InstitutionalTrusteeInd
0,tbd,Jandel Allen-Davis MD,"Member, BOD",2,0,X,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1,tbd,Sue Allon,"Member, BOD",2,0,X,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
2,tbd,Steve Arent,"Lifetime Member, BOD",0,0,X,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
3,tbd,Richard Baer,"Member, BOD",2,0,X,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,tbd,Geoffrey Barker,"Member, BOD",2,0,X,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12101,tbd,MARK WOOD,PRESIDENT,NaN,NaN,NaN,0,0,0,X,NaN,NaN,NaN,NaN,NaN
12102,tbd,STEPHEN BARNARD,PRESIDENT,1.00,NaN,X,0,0,0,X,NaN,NaN,NaN,NaN,NaN
12103,tbd,ANITA LEMOS,V.P.,1.00,NaN,X,0,0,0,X,NaN,NaN,NaN,NaN,NaN
12104,tbd,BRYAN GILES,TREASURER,1.00,NaN,X,0,0,0,X,NaN,NaN,NaN,NaN,NaN
12105,tbd,JOANNE WU,SECRETARY,1.00,NaN,X,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
pd.DataFrame(contractor_data)

,EIN,BusinessNameLine1Txt,AddressLine1Txt,AddressLine2Txt,CityNm,StateAbbreviationCd,ZIPCd,ServicesDesc,CompensationAmt,PersonNm,CountryCd,BusinessNameLine2Txt,ProvinceOrStateNm,ForeignPostalCd,ContractorAddress
0,tbd,Dimassimo,220 E 23rd Street,2nd Floor,New York,NY,10010,Advertising and Professional Fees,2203123,NaN,NaN,NaN,NaN,NaN,NaN
1,tbd,Siemens Medical Solutions USA Inc,51 Valley Stream Pkwy,NaN,Malvern,PA,19355,Equipment Maintenance Contract,1023832,NaN,NaN,NaN,NaN,NaN,NaN
2,tbd,HSS,MAIN,PO BOX 17033,Denver,CO,80217,Security Support,867767,NaN,NaN,NaN,NaN,NaN,NaN
3,tbd,ARUP Laboratories,MAIN,PO Box 27964,Salt Lake City,UT,84127,Lab Services,848779,NaN,NaN,NaN,NaN,NaN,NaN
4,tbd,Mindset Direct,12110 Sunset Hills Rd 600,NaN,Reston,VA,20190,Fundraising Servicses,612348,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
391,tbd,KENNETH MATTUS,1114 MAPLE STREET,NaN,SANTA MONICA,CA,90405,MUSIC PROGRAM SUPPORT,127140,NaN,NaN,NaN,NaN,NaN,NaN
392,tbd,Tuzinsky Consulting LLC,13741 Labelle St,NaN,Oak Park,MI,48237,Consulting,176325,NaN,NaN,NaN,NaN,NaN,NaN
393,tbd,MTAN Solutions LLC,966 Torke Terrace,NaN,Plymouth,MI,48170,Consulting,107250,NaN,NaN,NaN,NaN,NaN,NaN
394,tbd,Financial One Accounting Inc,44744 Helm St,NaN,Plymouth,MI,48170,Accounting Services,101076,NaN,NaN,NaN,NaN,NaN,NaN
395,tbd,NATIONAL HERITAGE ACADEMIES INC,3850 BROADMOOR AVENUE SE SUITE 201,NaN,GRAND RAPIDS,MI,49512,MANAGEMENT SERVICES,14012208,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
pd.DataFrame(expense_data)

,EIN,ExpenseType,TotalAmt,ProgramServicesAmt,ManagementAndGeneralAmt,FundraisingAmt
0,tbd,Grants_DomesticGroup,0,0,NaN,NaN
1,tbd,Grants_DomesticIndividuals,0,0,NaN,NaN
2,tbd,Compensation_CurrentOfficersDirectors,10636915,6002286,4137346,497283
3,tbd,Fees_Lobbying,154123,0,154123,0
4,tbd,Fees_ProfessionalFundraising,300840,NaN,NaN,300840
...,...,...,...,...,...,...
2407,tbd,Payment_TravelForPublicOfficials,0,0,0,0
2408,tbd,Compensation_CurrentOfficersDirectors,74472,36268,38204,NaN
2409,tbd,Grants_DomesticGroup,2076596,2076596,NaN,NaN
2410,tbd,Grants_DomesticIndividuals,2900,2900,NaN,NaN
2411,tbd,Grants_DomesticGroup,82300,82300,NaN,NaN

In [10]:
pd.DataFrame(balance_sheet_data)

,EIN,BalanceSheetSection,BalanceSheetSubsection,TotalAmt,ProgramServicesAmt,BOYAmt,EOYAmt
0,tbd,Assets,PledgesAndGrantsReceivable,0,0,NaN,NaN
1,tbd,Assets,TotalAssets,NaN,NaN,301872000,304229000
2,tbd,Liabilities,TotalLiabilities,NaN,NaN,88079000,77425000
3,tbd,NetAssetsOrFundBalances,NetAssets_Unrestricted,NaN,NaN,71082000,87606000
4,tbd,NetAssetsOrFundBalances,NetAssets_TemporarilyRestricted,NaN,NaN,90519000,85886000
...,...,...,...,...,...,...,...
4091,tbd,Liabilities,TotalLiabilities,NaN,NaN,0,0
4092,tbd,NetAssetsOrFundBalances,NetAssets_NoDonorRestrictions,NaN,NaN,210531,201416
4093,tbd,Assets,PledgesAndGrantsReceivable,82300,82300,NaN,NaN
4094,tbd,Assets,TotalAssets,NaN,NaN,80845,53390
4095,tbd,Liabilities,TotalLiabilities,NaN,NaN,0,0

Search files for instance that has target

In [ ]:
# NAMESPACE = '{http://www.irs.gov/efile}'
# RETURN_HEADER_PATH = f'./{NAMESPACE}ReturnHeader'
# PREPARER_FIRM_GROUP_PATH = f'./{NAMESPACE}PreparerFirmGrp'
# FILER_PATH = f'./{NAMESPACE}Filer'
# RETURN_DATA_PATH = f'./{NAMESPACE}ReturnData'
# IRS990_PATH = RETURN_DATA_PATH + f'/{NAMESPACE}IRS990'
# SCHEDULEA_PATH = f'./{NAMESPACE}IRS990ScheduleA'
# SCHEDULEC_PATH = f'./{NAMESPACE}IRS990ScheduleC'

# target = f'{NAMESPACE}OrganizationFollowsSFAS117Ind'

# for year_dir in xml_data_directory.iterdir():
#     for period_dir in year_dir.iterdir():
#         print(period_dir)
#         counter = 0
#         files_skipped = 0
#         for xml_file in period_dir.glob('*.xml'):
#             # Skip certain orgs and form types
#             root = ET.parse(xml_file).getroot()
#             org_type = get_org_type(root)
#             if org_type not in ['501c3', '501c4', '527']:
#                 files_skipped += 1
#                 continue

#             if '202011559349300711' in str(xml_file):
#                 continue

#             _990 = root.find(SCHEDULEC_PATH)
#             if _990 is not None:
#                 print(xml_file)
#                 raise TypeError
#             # target_text = _990.find(target).text
#             # if target_text not in ['false', '0', 'o', 'O']:
#             #     print(xml_file)
#             #     raise TypeError

xml\2020\2020_1A
xml\2020\2020_3A
xml\2024\2024_01A
xml\2024\2024_02A

KeyboardInterrupt:

Search files for instance that does NOT have target

In [12]:
NAMESPACE = '{http://www.irs.gov/efile}'
RETURN_HEADER_PATH = f'./{NAMESPACE}ReturnHeader'
PREPARER_FIRM_GROUP_PATH = f'./{NAMESPACE}PreparerFirmGrp'
FILER_PATH = f'./{NAMESPACE}Filer'
RETURN_DATA_PATH = f'./{NAMESPACE}ReturnData'
IRS990_PATH = RETURN_DATA_PATH + f'/{NAMESPACE}IRS990'

target = f'{NAMESPACE}OrganizationFollowsSFAS117Ind'

for year_dir in xml_data_directory.iterdir():
    for period_dir in year_dir.iterdir():
        print(period_dir)
        counter = 0
        files_skipped = 0
        for xml_file in period_dir.glob('*.xml'):
            # Skip certain orgs and form types
            root = ET.parse(xml_file).getroot()
            org_type = get_org_type(root)
            if org_type not in ['501c3', '501c4', '527']:
                files_skipped += 1
                continue 
            
            if '202011559349301216' in str(xml_file):
                continue
            
            _990 = root.find(IRS990_PATH)
            try:
                _990.find(target).text
            except AttributeError:
                print(xml_file)
                raise AttributeError

xml\2020\2020_1A
xml\2020\2020_3A
xml\2020\2020_3A\202011559349300716_public.xml

AttributeError:

In [13]:
data = []
counter = 0 
for year_dir in xml_data_directory.iterdir():
    for period_dir in year_dir.iterdir():
        print(period_dir)
        for xml_file in period_dir.glob('*.xml'):
            # Skip certain orgs and form types
            root = ET.parse(xml_file).getroot()
            org_type = get_org_type(root)
            if org_type not in ['501c3', '501c4', '527']:
                continue
            ReturnContent = {}
            # * Header
            Header = root.find(RETURN_HEADER_PATH)
            ReturnContent['EIN'] = Header.find(f'{NAMESPACE}Filer/{NAMESPACE}EIN').text
            ReturnContent['Name'] = Header.find(f'{NAMESPACE}Filer/{NAMESPACE}BusinessName/{NAMESPACE}BusinessNameLine1Txt').text
            ReturnContent['OrgType'] = org_type
            ReturnContent['file'] = str(xml_file)
            ReturnContent['TaxYr'] = Header.find(f'{NAMESPACE}TaxYr').text
            # * ReturnData
            ReturnData = root.find(RETURN_DATA_PATH)
            for section in ReturnData:
                ReturnContentKey = section.tag.replace(NAMESPACE, '')
                ReturnContent[ReturnContentKey] = 1
            data.append(ReturnContent)
            counter += 1
            if counter % 100 == 0:
                print(f'Parsed {counter} files.')

xml\2020\2020_1A
xml\2020\2020_3A
Parsed 100 files.
Parsed 200 files.
Parsed 300 files.
Parsed 400 files.
Parsed 500 files.
Parsed 600 files.
Parsed 700 files.
Parsed 800 files.
Parsed 900 files.
Parsed 1000 files.
Parsed 1100 files.
Parsed 1200 files.
Parsed 1300 files.
Parsed 1400 files.
Parsed 1500 files.
Parsed 1600 files.
Parsed 1700 files.
Parsed 1800 files.
Parsed 1900 files.
Parsed 2000 files.
Parsed 2100 files.
Parsed 2200 files.
Parsed 2300 files.
Parsed 2400 files.
Parsed 2500 files.
Parsed 2600 files.
Parsed 2700 files.
Parsed 2800 files.
Parsed 2900 files.
Parsed 3000 files.
Parsed 3100 files.
Parsed 3200 files.
Parsed 3300 files.
Parsed 3400 files.
Parsed 3500 files.
Parsed 3600 files.
Parsed 3700 files.
Parsed 3800 files.
Parsed 3900 files.
Parsed 4000 files.
Parsed 4100 files.
Parsed 4200 files.
Parsed 4300 files.
Parsed 4400 files.
Parsed 4500 files.
Parsed 4600 files.
Parsed 4700 files.
Parsed 4800 files.
Parsed 4900 files.
Parsed 5000 files.
Parsed 5100 files.
Parsed 5200 files.
Parsed 5300 files.
Parsed 5400 files.
Parsed 5500 files.
Parsed 5600 files.
Parsed 5700 files.
Parsed 5800 files.
Parsed 5900 files.
Parsed 6000 files.
Parsed 6100 files.
Parsed 6200 files.
Parsed 6300 files.
Parsed 6400 files.
Parsed 6500 files.
Parsed 6600 files.
Parsed 6700 files.
Parsed 6800 files.
Parsed 6900 files.
Parsed 7000 files.
Parsed 7100 files.
Parsed 7200 files.
Parsed 7300 files.
Parsed 7400 files.
Parsed 7500 files.
Parsed 7600 files.
Parsed 7700 files.
Parsed 7800 files.
Parsed 7900 files.
Parsed 8000 files.
Parsed 8100 files.
Parsed 8200 files.
Parsed 8300 files.
Parsed 8400 files.
Parsed 8500 files.
Parsed 8600 files.
Parsed 8700 files.
Parsed 8800 files.
Parsed 8900 files.
Parsed 9000 files.
Parsed 9100 files.
Parsed 9200 files.
Parsed 9300 files.
Parsed 9400 files.
Parsed 9500 files.
Parsed 9600 files.
Parsed 9700 files.
Parsed 9800 files.
Parsed 9900 files.
Parsed 10000 files.
Parsed 10100 files.
Parsed 10200 files.
Parsed 10300 files.
Parsed 10400 files.
Parsed 10500 files.
Parsed 10600 files.
Parsed 10700 files.
Parsed 10800 files.
Parsed 10900 files.
Parsed 11000 files.
Parsed 11100 files.
Parsed 11200 files.
Parsed 11300 files.
Parsed 11400 files.
Parsed 11500 files.
Parsed 11600 files.
Parsed 11700 files.
Parsed 11800 files.
Parsed 11900 files.
Parsed 12000 files.
Parsed 12100 files.
Parsed 12200 files.
Parsed 12300 files.
Parsed 12400 files.
Parsed 12500 files.
Parsed 12600 files.
Parsed 12700 files.
Parsed 12800 files.
Parsed 12900 files.
Parsed 13000 files.
Parsed 13100 files.
Parsed 13200 files.
Parsed 13300 files.
Parsed 13400 files.
Parsed 13500 files.
Parsed 13600 files.
Parsed 13700 files.
Parsed 13800 files.
Parsed 13900 files.
Parsed 14000 files.
Parsed 14100 files.
Parsed 14200 files.
Parsed 14300 files.
Parsed 14400 files.
Parsed 14500 files.
Parsed 14600 files.
Parsed 14700 files.
Parsed 14800 files.
Parsed 14900 files.
Parsed 15000 files.
Parsed 15100 files.
Parsed 15200 files.
Parsed 15300 files.
Parsed 15400 files.
Parsed 15500 files.
Parsed 15600 files.
Parsed 15700 files.
Parsed 15800 files.
Parsed 15900 files.
Parsed 16000 files.
Parsed 16100 files.
Parsed 16200 files.
Parsed 16300 files.
Parsed 16400 files.
Parsed 16500 files.
Parsed 16600 files.
Parsed 16700 files.
Parsed 16800 files.
Parsed 16900 files.
Parsed 17000 files.
Parsed 17100 files.
Parsed 17200 files.
Parsed 17300 files.
Parsed 17400 files.
Parsed 17500 files.
Parsed 17600 files.
Parsed 17700 files.
Parsed 17800 files.
Parsed 17900 files.
Parsed 18000 files.
Parsed 18100 files.
Parsed 18200 files.
Parsed 18300 files.
Parsed 18400 files.
Parsed 18500 files.
Parsed 18600 files.
Parsed 18700 files.
Parsed 18800 files.
Parsed 18900 files.
Parsed 19000 files.
Parsed 19100 files.
Parsed 19200 files.
Parsed 19300 files.
Parsed 19400 files.
Parsed 19500 files.
Parsed 19600 files.
Parsed 19700 files.
Parsed 19800 files.
Parsed 19900 files.
Parsed 20000 files.
Parsed 20100 files.
Parsed 20200 files.
Parsed 20300 files.
Parsed 20400 files.
Parsed 20500 files.
Parsed 20600 files.
Parsed 20700 files.
Parsed 20800 files.
Parsed 20900 files.
Parsed 21000 files.
Parsed 21100 files.
Parsed 21200 files.
Parsed 21300 files.
Parsed 21400 files.
Parsed 21500 files.
Parsed 21600 files.
Parsed 21700 files.
Parsed 21800 files.
Parsed 21900 files.
Parsed 22000 files.
Parsed 22100 files.
Parsed 22200 files.
Parsed 22300 files.
Parsed 22400 files.
Parsed 22500 files.
Parsed 22600 files.
Parsed 22700 files.
Parsed 22800 files.
Parsed 22900 files.
Parsed 23000 files.
Parsed 23100 files.
Parsed 23200 files.
Parsed 23300 files.
Parsed 23400 files.
Parsed 23500 files.
Parsed 23600 files.
Parsed 23700 files.
Parsed 23800 files.
Parsed 23900 files.
Parsed 24000 files.
Parsed 24100 files.
Parsed 24200 files.
Parsed 24300 files.
Parsed 24400 files.
Parsed 24500 files.
Parsed 24600 files.
Parsed 24700 files.
Parsed 24800 files.
Parsed 24900 files.
Parsed 25000 files.
Parsed 25100 files.
Parsed 25200 files.
Parsed 25300 files.
Parsed 25400 files.
Parsed 25500 files.
Parsed 25600 files.
Parsed 25700 files.
Parsed 25800 files.
Parsed 25900 files.
Parsed 26000 files.
Parsed 26100 files.
Parsed 26200 files.
Parsed 26300 files.
Parsed 26400 files.
Parsed 26500 files.
Parsed 26600 files.
Parsed 26700 files.
Parsed 26800 files.
Parsed 26900 files.
Parsed 27000 files.
Parsed 27100 files.
Parsed 27200 files.
Parsed 27300 files.
Parsed 27400 files.
Parsed 27500 files.
Parsed 27600 files.
Parsed 27700 files.
Parsed 27800 files.
Parsed 27900 files.
Parsed 28000 files.
xml\2024\2024_01A
Parsed 28100 files.
Parsed 28200 files.
Parsed 28300 files.
Parsed 28400 files.
Parsed 28500 files.
Parsed 28600 files.
Parsed 28700 files.
Parsed 28800 files.
Parsed 28900 files.
Parsed 29000 files.
Parsed 29100 files.
Parsed 29200 files.
Parsed 29300 files.
Parsed 29400 files.
Parsed 29500 files.
Parsed 29600 files.
Parsed 29700 files.
Parsed 29800 files.
Parsed 29900 files.
Parsed 30000 files.
Parsed 30100 files.
Parsed 30200 files.
Parsed 30300 files.
Parsed 30400 files.
Parsed 30500 files.
Parsed 30600 files.
Parsed 30700 files.
Parsed 30800 files.
Parsed 30900 files.
Parsed 31000 files.
Parsed 31100 files.
Parsed 31200 files.
Parsed 31300 files.
Parsed 31400 files.
Parsed 31500 files.
Parsed 31600 files.
Parsed 31700 files.
Parsed 31800 files.
Parsed 31900 files.
Parsed 32000 files.
Parsed 32100 files.
Parsed 32200 files.
Parsed 32300 files.
Parsed 32400 files.
Parsed 32500 files.
Parsed 32600 files.
Parsed 32700 files.
Parsed 32800 files.
Parsed 32900 files.
Parsed 33000 files.
Parsed 33100 files.
Parsed 33200 files.
Parsed 33300 files.
Parsed 33400 files.
Parsed 33500 files.
Parsed 33600 files.
Parsed 33700 files.
Parsed 33800 files.
Parsed 33900 files.
Parsed 34000 files.
Parsed 34100 files.
Parsed 34200 files.
Parsed 34300 files.
Parsed 34400 files.
Parsed 34500 files.
Parsed 34600 files.
Parsed 34700 files.
Parsed 34800 files.
Parsed 34900 files.
Parsed 35000 files.
Parsed 35100 files.
Parsed 35200 files.
Parsed 35300 files.
Parsed 35400 files.
Parsed 35500 files.
Parsed 35600 files.
Parsed 35700 files.
Parsed 35800 files.
xml\2024\2024_02A
Parsed 35900 files.
Parsed 36000 files.
Parsed 36100 files.
Parsed 36200 files.
Parsed 36300 files.
Parsed 36400 files.
Parsed 36500 files.
Parsed 36600 files.
Parsed 36700 files.
Parsed 36800 files.
Parsed 36900 files.
Parsed 37000 files.
Parsed 37100 files.
Parsed 37200 files.
Parsed 37300 files.
Parsed 37400 files.
Parsed 37500 files.
Parsed 37600 files.
Parsed 37700 files.
Parsed 37800 files.
Parsed 37900 files.
Parsed 38000 files.
Parsed 38100 files.
Parsed 38200 files.
Parsed 38300 files.
Parsed 38400 files.
Parsed 38500 files.
Parsed 38600 files.
Parsed 38700 files.
Parsed 38800 files.
Parsed 38900 files.
Parsed 39000 files.
Parsed 39100 files.
Parsed 39200 files.
Parsed 39300 files.
Parsed 39400 files.
Parsed 39500 files.
Parsed 39600 files.
Parsed 39700 files.
Parsed 39800 files.
Parsed 39900 files.
Parsed 40000 files.
Parsed 40100 files.
Parsed 40200 files.
Parsed 40300 files.
Parsed 40400 files.
Parsed 40500 files.
Parsed 40600 files.
Parsed 40700 files.
Parsed 40800 files.
Parsed 40900 files.
Parsed 41000 files.
Parsed 41100 files.
Parsed 41200 files.
Parsed 41300 files.
Parsed 41400 files.
Parsed 41500 files.
Parsed 41600 files.
Parsed 41700 files.
Parsed 41800 files.
Parsed 41900 files.
Parsed 42000 files.
Parsed 42100 files.
Parsed 42200 files.
Parsed 42300 files.
Parsed 42400 files.
Parsed 42500 files.
Parsed 42600 files.
Parsed 42700 files.
Parsed 42800 files.
Parsed 42900 files.
Parsed 43000 files.
Parsed 43100 files.
Parsed 43200 files.
Parsed 43300 files.
Parsed 43400 files.
Parsed 43500 files.
Parsed 43600 files.
Parsed 43700 files.
Parsed 43800 files.
Parsed 43900 files.
Parsed 44000 files.
Parsed 44100 files.
Parsed 44200 files.
Parsed 44300 files.
Parsed 44400 files.
Parsed 44500 files.
Parsed 44600 files.
Parsed 44700 files.
Parsed 44800 files.
Parsed 44900 files.
Parsed 45000 files.
Parsed 45100 files.
Parsed 45200 files.
Parsed 45300 files.
Parsed 45400 files.
Parsed 45500 files.
Parsed 45600 files.
Parsed 45700 files.
Parsed 45800 files.
Parsed 45900 files.
Parsed 46000 files.
Parsed 46100 files.
Parsed 46200 files.
Parsed 46300 files.
Parsed 46400 files.
Parsed 46500 files.
Parsed 46600 files.
Parsed 46700 files.
Parsed 46800 files.
Parsed 46900 files.
Parsed 47000 files.
Parsed 47100 files.
Parsed 47200 files.
Parsed 47300 files.
Parsed 47400 files.
Parsed 47500 files.
Parsed 47600 files.
Parsed 47700 files.
Parsed 47800 files.
Parsed 47900 files.
Parsed 48000 files.
Parsed 48100 files.
Parsed 48200 files.
Parsed 48300 files.
Parsed 48400 files.
Parsed 48500 files.
Parsed 48600 files.
Parsed 48700 files.
Parsed 48800 files.
Parsed 48900 files.
Parsed 49000 files.
Parsed 49100 files.
Parsed 49200 files.
Parsed 49300 files.
Parsed 49400 files.
Parsed 49500 files.
Parsed 49600 files.
Parsed 49700 files.
Parsed 49800 files.
Parsed 49900 files.
Parsed 50000 files.
Parsed 50100 files.
Parsed 50200 files.
Parsed 50300 files.
Parsed 50400 files.
Parsed 50500 files.
Parsed 50600 files.
Parsed 50700 files.
Parsed 50800 files.
Parsed 50900 files.
Parsed 51000 files.
Parsed 51100 files.
Parsed 51200 files.
Parsed 51300 files.
Parsed 51400 files.
Parsed 51500 files.
Parsed 51600 files.
Parsed 51700 files.
Parsed 51800 files.
Parsed 51900 files.
Parsed 52000 files.
Parsed 52100 files.
Parsed 52200 files.
Parsed 52300 files.
Parsed 52400 files.
Parsed 52500 files.
Parsed 52600 files.
Parsed 52700 files.
Parsed 52800 files.
xml\2025\2025_01A
Parsed 52900 files.
Parsed 53000 files.
Parsed 53100 files.
Parsed 53200 files.
Parsed 53300 files.
Parsed 53400 files.
Parsed 53500 files.
Parsed 53600 files.
Parsed 53700 files.
Parsed 53800 files.
Parsed 53900 files.
Parsed 54000 files.
Parsed 54100 files.
Parsed 54200 files.
Parsed 54300 files.
Parsed 54400 files.
Parsed 54500 files.
Parsed 54600 files.
Parsed 54700 files.
Parsed 54800 files.
Parsed 54900 files.
Parsed 55000 files.
Parsed 55100 files.
Parsed 55200 files.
Parsed 55300 files.
Parsed 55400 files.
Parsed 55500 files.
Parsed 55600 files.
Parsed 55700 files.
Parsed 55800 files.
Parsed 55900 files.
Parsed 56000 files.
Parsed 56100 files.
Parsed 56200 files.
Parsed 56300 files.
Parsed 56400 files.
Parsed 56500 files.
Parsed 56600 files.
Parsed 56700 files.
Parsed 56800 files.
Parsed 56900 files.
Parsed 57000 files.
Parsed 57100 files.
Parsed 57200 files.
Parsed 57300 files.
Parsed 57400 files.
Parsed 57500 files.
Parsed 57600 files.
Parsed 57700 files.
Parsed 57800 files.
Parsed 57900 files.
Parsed 58000 files.
Parsed 58100 files.
Parsed 58200 files.
Parsed 58300 files.
Parsed 58400 files.
Parsed 58500 files.
Parsed 58600 files.
Parsed 58700 files.
Parsed 58800 files.
Parsed 58900 files.
Parsed 59000 files.
Parsed 59100 files.
Parsed 59200 files.
Parsed 59300 files.
Parsed 59400 files.
Parsed 59500 files.
Parsed 59600 files.
Parsed 59700 files.
Parsed 59800 files.
Parsed 59900 files.
Parsed 60000 files.
Parsed 60100 files.
Parsed 60200 files.
Parsed 60300 files.
xml\2025\2025_02A
Parsed 60400 files.
Parsed 60500 files.
Parsed 60600 files.
Parsed 60700 files.
Parsed 60800 files.
Parsed 60900 files.
Parsed 61000 files.
Parsed 61100 files.
Parsed 61200 files.
Parsed 61300 files.
Parsed 61400 files.
Parsed 61500 files.
Parsed 61600 files.
Parsed 61700 files.
Parsed 61800 files.
Parsed 61900 files.
Parsed 62000 files.
Parsed 62100 files.
Parsed 62200 files.
Parsed 62300 files.
Parsed 62400 files.
Parsed 62500 files.
Parsed 62600 files.
Parsed 62700 files.
Parsed 62800 files.
Parsed 62900 files.
Parsed 63000 files.
Parsed 63100 files.
Parsed 63200 files.
Parsed 63300 files.
Parsed 63400 files.
Parsed 63500 files.
Parsed 63600 files.
Parsed 63700 files.
Parsed 63800 files.
Parsed 63900 files.
Parsed 64000 files.
Parsed 64100 files.
Parsed 64200 files.
Parsed 64300 files.
Parsed 64400 files.
Parsed 64500 files.
Parsed 64600 files.
Parsed 64700 files.
Parsed 64800 files.
Parsed 64900 files.
Parsed 65000 files.
Parsed 65100 files.
Parsed 65200 files.
Parsed 65300 files.
Parsed 65400 files.
Parsed 65500 files.
Parsed 65600 files.
Parsed 65700 files.
Parsed 65800 files.
Parsed 65900 files.
Parsed 66000 files.
Parsed 66100 files.
Parsed 66200 files.
Parsed 66300 files.
Parsed 66400 files.
Parsed 66500 files.
Parsed 66600 files.
Parsed 66700 files.
Parsed 66800 files.
Parsed 66900 files.
Parsed 67000 files.
Parsed 67100 files.
Parsed 67200 files.
Parsed 67300 files.
Parsed 67400 files.
Parsed 67500 files.
Parsed 67600 files.
Parsed 67700 files.
Parsed 67800 files.
Parsed 67900 files.
Parsed 68000 files.
Parsed 68100 files.
Parsed 68200 files.
Parsed 68300 files.
Parsed 68400 files.
Parsed 68500 files.
Parsed 68600 files.
Parsed 68700 files.
Parsed 68800 files.
Parsed 68900 files.
Parsed 69000 files.
Parsed 69100 files.
Parsed 69200 files.
Parsed 69300 files.
Parsed 69400 files.
Parsed 69500 files.
Parsed 69600 files.
Parsed 69700 files.
Parsed 69800 files.
Parsed 69900 files.
Parsed 70000 files.
Parsed 70100 files.
Parsed 70200 files.
Parsed 70300 files.
Parsed 70400 files.
Parsed 70500 files.
Parsed 70600 files.
Parsed 70700 files.
Parsed 70800 files.
Parsed 70900 files.
Parsed 71000 files.
Parsed 71100 files.
Parsed 71200 files.
Parsed 71300 files.
Parsed 71400 files.
Parsed 71500 files.
Parsed 71600 files.
Parsed 71700 files.
Parsed 71800 files.
Parsed 71900 files.
Parsed 72000 files.
Parsed 72100 files.
Parsed 72200 files.
Parsed 72300 files.
Parsed 72400 files.
Parsed 72500 files.
Parsed 72600 files.
Parsed 72700 files.
Parsed 72800 files.
Parsed 72900 files.
Parsed 73000 files.
Parsed 73100 files.
Parsed 73200 files.
Parsed 73300 files.
Parsed 73400 files.
Parsed 73500 files.
Parsed 73600 files.
Parsed 73700 files.
Parsed 73800 files.
Parsed 73900 files.
Parsed 74000 files.
Parsed 74100 files.
Parsed 74200 files.
Parsed 74300 files.
Parsed 74400 files.
Parsed 74500 files.
Parsed 74600 files.
Parsed 74700 files.
Parsed 74800 files.
Parsed 74900 files.
Parsed 75000 files.
Parsed 75100 files.
Parsed 75200 files.
Parsed 75300 files.
Parsed 75400 files.
Parsed 75500 files.
Parsed 75600 files.
Parsed 75700 files.
Parsed 75800 files.
Parsed 75900 files.
Parsed 76000 files.
Parsed 76100 files.
Parsed 76200 files.
Parsed 76300 files.
Parsed 76400 files.
Parsed 76500 files.
Parsed 76600 files.
Parsed 76700 files.
Parsed 76800 files.
Parsed 76900 files.
Parsed 77000 files.
Parsed 77100 files.
Parsed 77200 files.
Parsed 77300 files.
Parsed 77400 files.
Parsed 77500 files.
Parsed 77600 files.
Parsed 77700 files.
Parsed 77800 files.
Parsed 77900 files.
Parsed 78000 files.
xml\2025\2025_03A
Parsed 78100 files.
Parsed 78200 files.
Parsed 78300 files.
Parsed 78400 files.
Parsed 78500 files.
Parsed 78600 files.
Parsed 78700 files.
Parsed 78800 files.
Parsed 78900 files.
Parsed 79000 files.
Parsed 79100 files.
Parsed 79200 files.
Parsed 79300 files.
Parsed 79400 files.
Parsed 79500 files.
Parsed 79600 files.
Parsed 79700 files.
Parsed 79800 files.
Parsed 79900 files.
Parsed 80000 files.
Parsed 80100 files.
Parsed 80200 files.
Parsed 80300 files.
Parsed 80400 files.
Parsed 80500 files.
Parsed 80600 files.
Parsed 80700 files.
Parsed 80800 files.
Parsed 80900 files.
Parsed 81000 files.
Parsed 81100 files.
Parsed 81200 files.
Parsed 81300 files.
Parsed 81400 files.
Parsed 81500 files.
Parsed 81600 files.
Parsed 81700 files.
Parsed 81800 files.
Parsed 81900 files.
Parsed 82000 files.
Parsed 82100 files.
Parsed 82200 files.
Parsed 82300 files.
Parsed 82400 files.
Parsed 82500 files.
Parsed 82600 files.
Parsed 82700 files.
Parsed 82800 files.
Parsed 82900 files.
Parsed 83000 files.
Parsed 83100 files.
Parsed 83200 files.
Parsed 83300 files.
Parsed 83400 files.
Parsed 83500 files.
Parsed 83600 files.
Parsed 83700 files.
Parsed 83800 files.
Parsed 83900 files.
Parsed 84000 files.
Parsed 84100 files.
Parsed 84200 files.
Parsed 84300 files.
Parsed 84400 files.
Parsed 84500 files.
Parsed 84600 files.
Parsed 84700 files.
Parsed 84800 files.
Parsed 84900 files.
Parsed 85000 files.
Parsed 85100 files.
Parsed 85200 files.
Parsed 85300 files.
Parsed 85400 files.
Parsed 85500 files.
Parsed 85600 files.
Parsed 85700 files.
Parsed 85800 files.
Parsed 85900 files.
Parsed 86000 files.
Parsed 86100 files.
Parsed 86200 files.
Parsed 86300 files.
Parsed 86400 files.
Parsed 86500 files.
Parsed 86600 files.
Parsed 86700 files.
Parsed 86800 files.
Parsed 86900 files.
Parsed 87000 files.
Parsed 87100 files.
Parsed 87200 files.
Parsed 87300 files.
Parsed 87400 files.
Parsed 87500 files.
Parsed 87600 files.
Parsed 87700 files.
Parsed 87800 files.
Parsed 87900 files.
Parsed 88000 files.
Parsed 88100 files.
Parsed 88200 files.
Parsed 88300 files.
Parsed 88400 files.
Parsed 88500 files.
Parsed 88600 files.
Parsed 88700 files.
Parsed 88800 files.
Parsed 88900 files.
Parsed 89000 files.
Parsed 89100 files.
Parsed 89200 files.
Parsed 89300 files.
Parsed 89400 files.
Parsed 89500 files.
Parsed 89600 files.
Parsed 89700 files.
Parsed 89800 files.
Parsed 89900 files.
Parsed 90000 files.
Parsed 90100 files.
Parsed 90200 files.
Parsed 90300 files.
Parsed 90400 files.
Parsed 90500 files.
Parsed 90600 files.
Parsed 90700 files.
Parsed 90800 files.
Parsed 90900 files.
Parsed 91000 files.
Parsed 91100 files.
Parsed 91200 files.
Parsed 91300 files.
Parsed 91400 files.
Parsed 91500 files.
Parsed 91600 files.
Parsed 91700 files.
Parsed 91800 files.
Parsed 91900 files.
Parsed 92000 files.
Parsed 92100 files.
Parsed 92200 files.
Parsed 92300 files.
Parsed 92400 files.
Parsed 92500 files.
Parsed 92600 files.
Parsed 92700 files.
Parsed 92800 files.
Parsed 92900 files.
xml\2025\2025_04A
Parsed 93000 files.
Parsed 93100 files.
Parsed 93200 files.
Parsed 93300 files.
Parsed 93400 files.
Parsed 93500 files.
Parsed 93600 files.
Parsed 93700 files.
Parsed 93800 files.
Parsed 93900 files.
Parsed 94000 files.
Parsed 94100 files.
Parsed 94200 files.
Parsed 94300 files.
Parsed 94400 files.
Parsed 94500 files.
Parsed 94600 files.
Parsed 94700 files.
Parsed 94800 files.
Parsed 94900 files.
Parsed 95000 files.
Parsed 95100 files.
Parsed 95200 files.
Parsed 95300 files.
Parsed 95400 files.
Parsed 95500 files.
Parsed 95600 files.
Parsed 95700 files.
Parsed 95800 files.
Parsed 95900 files.
Parsed 96000 files.
Parsed 96100 files.
Parsed 96200 files.
Parsed 96300 files.
Parsed 96400 files.
Parsed 96500 files.
Parsed 96600 files.
Parsed 96700 files.
Parsed 96800 files.
Parsed 96900 files.
Parsed 97000 files.
Parsed 97100 files.
Parsed 97200 files.
Parsed 97300 files.
Parsed 97400 files.
Parsed 97500 files.
Parsed 97600 files.
Parsed 97700 files.
Parsed 97800 files.
Parsed 97900 files.
Parsed 98000 files.
Parsed 98100 files.
Parsed 98200 files.
Parsed 98300 files.
Parsed 98400 files.
Parsed 98500 files.
Parsed 98600 files.
Parsed 98700 files.
Parsed 98800 files.
Parsed 98900 files.
Parsed 99000 files.
Parsed 99100 files.
Parsed 99200 files.
Parsed 99300 files.
Parsed 99400 files.
Parsed 99500 files.
Parsed 99600 files.
Parsed 99700 files.
Parsed 99800 files.

In [ ]:
filing_content_matrix = pd.DataFrame(data)
filing_content_matrix.loc[:, 'file'] = filing_content_matrix.loc[:, 'file'].apply(lambda x: '\\'.join(x.split('\\')[2:]))
filing_content_matrix[filing_content_matrix.isna()] = 0
cols_to_convert = [col for col in filing_content_matrix.columns if col not in ['EIN', 'Name', 'OrgType', 'file']]
for col in cols_to_convert:
    filing_content_matrix[col] = filing_content_matrix[col].astype(int)
filing_content_matrix.to_csv('filing_content_matrix.csv')

In [25]:
filing_content_matrix

,EIN,Name,OrgType,file,TaxYr,IRS990,IRS990ScheduleA,IRS990ScheduleC,IRS990ScheduleD,IRS990ScheduleG,...,IRS990ScheduleB,IRS990ScheduleI,IRS990ScheduleF,AffiliatedGroupAttachment,IRS990ScheduleE,ReasonableCauseExplanation,IRS990ScheduleN,AveragingAttachment,AffiliatedGroupSchedule,AffiliateListing
0,742044647,NATIONAL JEWISH HEALTH,501c3,xml\2020\2020_3A\202011559349300711_public.xml,2018,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
1,581416325,HAWTREE VOLUNTEER FIRE DEPARTMENT INC,501c3,xml\2020\2020_3A\202011559349300716_public.xml,2019,1,1,0,1,0,...,1,0,0,0,0,0,0,0,0,0
2,223139262,RURAL DEVELOPMENT INC,501c3,xml\2020\2020_3A\202011559349300726_public.xml,2018,1,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,363244264,WILL COUNTY GOVERNMENTAL LEAGUE,501c4,xml\2020\2020_3A\202011559349300731_public.xml,2018,1,0,1,0,1,...,1,0,0,0,0,0,0,0,0,0
4,043316917,I'M STILL HERE FOUNDATION INC,501c3,xml\2020\2020_3A\202011559349300736_public.xml,2019,1,1,0,0,0,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413994,431556293,CIEFA MINISTRY INTERNATIONAL,501c3,xml\2026\2026_4A\202641139349301959_public.xml,2025,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
413995,260637571,ARMS OF CARE INTERNATIONAL INC,501c3,xml\2026\2026_4A\202641139349302004_public.xml,2025,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
413996,382878506,Christ Centered Homes Inc,501c3,xml\2026\2026_4A\202641139349302009_public.xml,2024,1,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
413997,330416470,HABITAT FOR HUMANITY OF GREATER,501c3,xml\2026\2026_4A\202641139349302054_public.xml,2024,1,1,0,1,1,...,1,0,0,0,0,0,0,0,0,0
413998,951945256,Episcopal Community Services,501c3,xml\2026\2026_4A\202641139349302059_public.xml,2024,1,1,1,1,1,...,1,1,0,0,0,0,0,0,0,0