In [1]:
import xml.etree.ElementTree as ET
from pathlib import Path
import json
import pandas as pd
from form990_parser import (
    parse_header,
    parse_return
)

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
xml_data_directory = Path(r'xml')

In [4]:
header_data = []
return_data = []
for year_dir in xml_data_directory.iterdir():
    for period_dir in year_dir.iterdir():
        print(period_dir)
        for i, xml_file in enumerate(period_dir.glob('*.xml')):
            if i == 50:
                break
                # pass
            root = ET.parse(xml_file).getroot()

            # * Header
            header_content = parse_header(root)
            header_data.append(header_content)
            
            # * Return
            return_content = parse_return(root)
            if return_content is None:
                continue # Some files pertain to other types of returns (e.g., 990-T)
            return_data.append(return_content)

xml\2020\2020_1A
xml\2020\2020_3A
xml\2026\2026_3A
xml\2026\2026_4A

In [5]:
pd.DataFrame(header_data)

,FilerEIN,TaxPeriodBeginDate,TaxPeriodEndDate,TaxYear,ReturnType,FilerBusinessNameLine1Txt,FilerBusinessNameLine2Txt,FilerPhone,FilerAddressLine1Txt,FilerCity,...,PreparerBusinessNameLine2Txt,PreparerAddressLine1Txt,PreparerCity,PreparerStateCode,PreparerZipCode,BusinessOfficerName,BusinessOfficerTitle,BusinessOfficerPhone,BusinessOfficerSignatureDate,NumOfficers
0,742044647,2018-07-01,2019-06-30,2018,990,NATIONAL JEWISH HEALTH,NaN,3033884461,1400 JACKSON STREET,DENVER,...,None,NaN,NaN,NaN,NaN,Christine Forkner,Chief Financial Officer,3033981004,2020-06-02,1
1,581416325,2019-01-01,2019-12-31,2019,990,HAWTREE VOLUNTEER FIRE DEPARTMENT INC,NaN,2522573288,PO BOX 116,WISE,...,None,PO BOX 177,HENDERSON,NC,27536,STEVE BARNEY,CHIEF,2524325386,2020-05-27,1
2,930306515,2019-01-01,2019-12-31,2019,990,International Brotherhood of Teamsters,206 TCWH,5032512344,1860 NE 162nd Avenue,Portland,...,None,9725 SW Bvtn-Hlsdl Hwy 220,Beaverton,OR,97005,Gene Blackburn,Secretary Treasurer,NaN,2020-06-03,1
3,223139262,2018-07-01,2019-06-30,2018,990,RURAL DEVELOPMENT INC,NaN,4138639781,241 MILLERS FALLS ROAD,TURNERS FALLS,...,None,50 WASHINGTON STREET,WESTBOROUGH,MA,01581,GINA GOVONI,EXECUTIVE DIRECTOR,4138639781,2020-05-06,1
4,363244264,2018-07-01,2019-06-30,2018,990,WILL COUNTY GOVERNMENTAL LEAGUE,NaN,8152547700,15905 S FREDERICK STREET Suite 107,PLAINFIELD,...,None,1901 S Meyers Road Suite 500,Oakbrook Terrace,IL,601815209,JOHN NOAK,PRESIDENT,8157293535,2020-05-15,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,922600437,2025-01-01,2025-12-31,2025,990PF,Gracie Graces Boots and Hearts Foundation,NaN,8502947792,10 Southern Hills Court,Graford,...,None,3641 Moline Court,Monrovia,MD,21770,Melissa Russell,President,8502947792,2026-03-26,1
146,956999192,2025-01-01,2025-12-31,2025,990PF,LORRAINE F PETITFILS FOUNDATION,NaN,6265777231,1285 WELLINGTON AVENUE,PASADENA,...,None,180 S Lake Avenue Ste 600,Pasadena,CA,91101,DENISE L PETITFILS,President,NaN,2026-03-27,1
147,137200887,2024-09-01,2025-08-31,2024,990PF,DAVID HIMELBERG FOUNDATION,NaN,2122970400,COHNREZNICK 1301 AVE OF AMERICAS,NEW YORK,...,None,1301 AVENUE OF THE AMERICAS,NEW YORK,NY,10019,NORMAN HIMELBERG,TRUSTEE,2122970400,2026-03-24,1
148,333456404,2025-01-01,2025-12-31,2025,990PF,Ronnie Foundation Inc,NaN,2245450018,2280 BROCKWAY ST,Rolling Mdws,...,None,NaN,NaN,NaN,NaN,Nicholas Klezek,President,2245450018,2026-03-27,1
149,464347632,2025-01-01,2025-12-31,2025,990PF,Mohapatra Family Foundation Inc,NaN,5186405000,C/O GOLDMAN SACHS AYCO PO Box 15201,Albany,...,None,ONE MANHATTAN WEST,NEW YORK,NY,10001,Surya Mohapatra,TRUSTEE,5186405000,2026-03-12,1

In [6]:
pd.DataFrame(return_data).head()

,PrincipalOfficer,PrincipalOfficerAddress,PrincipalOfficerCity,PrincipalOfficerStateCode,PrincipalOfficerZipCode,GrossReceiptsAmt,ActivityOrMission,MissionDesc,FormationYear,VotingMembersGoverningBodyCnt,...,PreviousYearTotalExpensesAmt,CurrentYearTotalExpensesAmt,PreviousYearRevenuesLessExpensesAmt,CurrentYearRevenuesLessExpensesAmt,TotalAssetsBeginningOfYearAmt,TotalAssetsEndOfYearAmt,TotalLiabilitiesBeginningOfYearAmt,TotalLiabilitiesEndOfYearAmt,NetAssetsOrFundBalancesBeginningOfYearAmt,NetAssetsOrFundBalancesEndOfYearAmt
0,Christine Forkner,1400 Jackson Street,Denver,CO,80206,326863373,National Jewish Health's mission since 1899 is...,National Jewish Health's mission since 1899 is...,1978,44,...,261433024,284109927,16825123,14092113,301872000,304229000,88079000,77425000,213793000,226804000
1,STEVE BARNEY,PO BOX 116,WISE,NC,27594,107616,TO PROVIDE FIRE DEPARTMENT SERVICES FOR THE CO...,TO PROVIDE FIRE DEPARTMENT SERVICES FOR THE CO...,1981,9,...,103953,113655,9709,-9658,525190,544937,341074,370479,184116,174458
2,NaN,1860 NE 162nd Avenue,Portland,OR,97230,1804349,"To secure improved wages, hours, working condi...","To secure improved wages, hours, working condi...",1937,7,...,1820769,1620608,-6726,183741,1361698,1547775,NaN,2336,1361698,1545439
3,GINA GOVONI,241 MILLERS FALLS ROAD,TURNERS FALLS,MA,01376,301633,"IT IS THE MISSION OF RURAL DEVELOPMENT, INC. (...",IT IS THE MISSION OF RDI TO ADVANCE THE RIGHT ...,1991,8,...,562061,576482,-233514,-274849,3582981,3432475,2761569,2885912,821412,546563
4,JOHN NOAK,15905 S FREDRICK STREET 107,PLAINFIELD,IL,60586,740025,GOVERNMENT SERVICE,THE WILL COUNTY GOVERNMENTAL LEAGUE IS ORGANIZ...,1983,9,...,566637,653709,1294,10425,593942,604367,0,0,593942,604367